export const eventMappings = {
  "Start the appeal": "startAppeal",
  "Aria Create Case": "ariaCreateCase",
  "Edit appeal": [
    "editAppeal",
    "editAppealAfterSubmit"
  ],
  "Submit your appeal": "submitAppeal",
  "Send direction": [
    "sendDirection",
    "sendBailDirection"
  ],
  "Change a direction due date": "changeDirectionDueDate",
  "Request respondent evidence": "requestRespondentEvidence",
  "Upload respondent evidence": "uploadRespondentEvidence",
  "Upload Home Office bundle": "uploadHomeOfficeBundle",
  "Request case building": "requestCaseBuilding",
  "Force request case building": "forceRequestCaseBuilding",
  "Build your case": "buildCase",
  "Submit your case": "submitCase",
  "Request case edit": "requestCaseEdit",
  "Request respondent review": "requestRespondentReview",
  "Add appeal response": "addAppealResponse",
  "Upload the appeal response": "uploadHomeOfficeAppealResponse",
  "Review Home Office response": "requestResponseReview",
  "Amend appeal response": "requestResponseAmend",
  "Request hearing requirements": [
    "requestHearingRequirements",
    "requestHearingRequirementsFeature",
    "requestNewHearingRequirements"
  ],
  "Upload additional evidence": [
    "uploadAdditionalEvidence",
    "uploadAdditionalEvidenceHomeOffice",
    "uploadAddendumEvidence",
    "uploadAddendumEvidenceLegalRep",
    "uploadAddendumEvidenceHomeOffice",
    "uploadAddendumEvidenceAdminOfficer"
  ],
  "List the case": "listCase",
  "List without requirements": "listCaseWithoutHearingRequirements",
  "Create case summary": "createCaseSummary",
  "Add additional evidence": "revertStateToAwaitingRespondentEvidence",
  "Generate hearing bundle": "generateHearingBundle",
  "Stitching bundle complete": "asyncStitchingComplete",
  "Start decision and reasons": "decisionAndReasonsStarted",
  "Prepare Decision and Reasons": "generateDecisionAndReasons",
  "Complete decision and reasons": "sendDecisionAndReasons",
  "Add case note": "addCaseNote",
  "Edit case listing": "editCaseListing",
  "Record an application": "recordApplication",
  "Record attendees and duration": "recordAttendeesAndDuration",
  "End the appeal": "endAppeal",
  "End Appeal Remission Rejected": "endAppealAutomatically",
  "Reinstate the appeal": "reinstateAppeal",
  "Submit hearing requirements": "draftHearingRequirements",
  "Update hearing requirements": "updateHearingRequirements",
  "Move appeal offline": "removeAppealFromOnline",
  "Share case with colleague": "shareACase",
  "Review hearing requirements": "reviewHearingRequirements",
  "AiP - Request Appeal Reasons": "requestReasonsForAppeal",
  "AiP - Edit Appeal Reasons": "editReasonsForAppeal",
  "Submit reasons for appeal": "submitReasonsForAppeal",
  "Update hearing adjustments": "updateHearingAdjustments",
  "Upload hearing recording": "uploadHearingRecording",
  "Send to pre hearing": "sendToPreHearing",
  "Change hearing centre": "changeHearingCentre",
  "Apply for permission to appeal": [
    "applyForFTPAAppellant",
    "applyForFTPARespondent"
  ],
  "Edit documents": [
    "editDocuments",
    "editBailDocuments"
  ],
  "Record allocated Judge": "recordAllocatedJudge",
  "Edit time extension": "editTimeExtension",
  "Review time extension": "reviewTimeExtension",
  "Request time extension": "submitTimeExtension",
  "Leadership judge FTPA decision": "leadershipJudgeFtpaDecision",
  "Resident judge FTPA decision": "residentJudgeFtpaDecision",
  "Decide FTPA application": "decideFtpaApplication",
  "AiP - Ask clarifying questions": "sendDirectionWithQuestions",
  "Edit clarifying answers": "editClarifyingQuestionAnswers",
  "Submit clarifying answers": "submitClarifyingQuestionAnswers",
  "Flag the case": "flagCase",
  "Remove a flag": "removeFlag",
  "Request CMA requirements": "requestCmaRequirements",
  "Link cases": "createCaseLink",
  "Maintain Case Links": [
    "maintainCaseLinks",
    "maintainBailCaseLinks"
  ],
  "edit CMA requirements": "editCmaRequirements",
  "Submit CMA requirements": "submitCmaRequirements",
  "Review CMA requirements": "reviewCmaRequirements",
  "List the appointment": "listCma",
  "Update details after CMA": "updateDetailsAfterCma",
  "Force case - case under review": "forceCaseToCaseUnderReview",
  "Force case - hearing reqs": "forceCaseToSubmitHearingRequirements",
  "Update representative details": [
    "updateLegalRepDetails",
    "updateBailLegalRepDetails"
  ],
  "Adjourn hearing without a date": "adjournHearingWithoutDate",
  "Restore to previous state": "restoreStateFromAdjourn",
  "Decision without a hearing": "decisionWithoutHearing",
  "Make a payment": "paymentAppeal",
  "Mark appeal as paid": "markAppealPaid",
  "Mark appeal as not paid": "moveToPaymentPending",
  "Rollback payment status": [
    "rollbackPayment",
    "rollbackPaymentTimeout",
    "rollbackPaymentTimeoutToPaymentPending"
  ],
  "Customise hearing bundle": "customiseHearingBundle",
  "Update Hearing Bundle": "generateUpdatedHearingBundle",
  "Upload sensitive documents": "uploadSensitiveDocuments",
  "Request Home Office data": "requestHomeOfficeData",
  "Make an application": "makeAnApplication",
  "Decide an application": "decideAnApplication",
  "Allocate the case": "allocateTheCase",
  "Record remission decision": "recordRemissionDecision",
  "Record remission reminder": "recordRemissionReminder",
  "Manage a fee update": "manageFeeUpdate",
  "NoC Request": "nocRequest",
  "Apply NoC Decision": "applyNocDecision",
  "Stop representing a client": [
    "removeRepresentation",
    "stopLegalRepresenting"
  ],
  "Remove legal representative": [
    "removeLegalRepresentative",
    "removeBailLegalRepresentative"
  ],
  "Request a fee remission": "requestFeeRemission",
  "Record out of time decision": "recordOutOfTimeDecision",
  "Generate Upper Tribunal bundle": "generateUpperTribunalBundle",
  "Mark evidence as reviewed": [
    "markEvidenceAsReviewed",
    "markAddendumEvidenceAsReviewed"
  ],
  "Update payment status": "updatePaymentStatus",
  "Draft hearing requirements UI": "editAipHearingRequirements",
  "Complete Clarifying Questions": "completeClarifyQuestions",
  "Mark payment request sent": "markPaymentRequestSent",
  "Create a service request": "generateServiceRequest",
  "PiP Activation": "pipActivation",
  "Pay and submit": "payAndSubmitAppeal",
  "migrate case": "migrateCase",
  "Strategic flags migration": "migrateToStrategicCaseFlags",
  "Legacy case flags clearing": "migrateClearLegacyCaseFlags",
  "Create Flag": "createFlag",
  "Manage Flags": "manageFlags",
  "Update s94b status": "updateS94bStatus",
  "Update interpreter status": "updateInterpreterBookingStatus",
  "Update interpreter details": "updateInterpreterDetails",
  "Update hearing request": "updateHearingRequest",
  "Handle hearing exception": "handleHearingException",
  "Trigger CMR Updated": "triggerCmrUpdated",
  "For functional test use only": "listCaseForFTOnly",
  "Record adjournment details": "recordAdjournmentDetails",
  "List Assist Integration": "listAssistIntegration",
  "Update Tribunal decision": "updateTribunalDecision",
  "Trigger CMR Listed": "triggerCmrListed",
  "Trigger Review Interpreter": "triggerReviewInterpreterBookingTask",
  "Decision w/o hearing Listed": "decisionWithoutHearingListed",
  "Re-trigger WA Tasks for case": "reTriggerWaTasks",
  "Re-trigger Task For Case IDs": "reTriggerWaBulkTasks",
  "Mark appeal as remitted": "markAppealAsRemitted",
  "Set next hearing date": "setNextHearingDate",
  "Payment reminder notification": "sendPaymentReminderNotification",
  "Progress Migrated Case": "progressMigratedCase",
  "Refund confirmation": "refundConfirmation",
  "Revoke case access": "revokeCaseAccess",
  "Save notifications to data": "saveNotificationsToData",
  "Manage Case TTL": "ManageTTL",
  // Bail specific
  "Start the application": "startApplication",
  "Submit the application": "submitApplication",
  "Upload Bail Summary": "uploadBailSummary",
  "Record the decision event": "recordTheDecision",
  "Upload signed decision notice": "uploadSignedDecisionNotice",
  "Upload signed decision notice Conditional Bail": "uploadSignedDecisionNoticeConditionalGrant",
  "Move application to decided": "moveApplicationToDecided",
  "End the application": "endApplication",
  "Upload documents": "uploadDocuments",
  "Make new application": "makeNewApplication",
  "Change bail direction due date": "changeBailDirectionDueDate",
  "Edit the application": [
    "editBailApplication",
    "editBailApplicationAfterSubmit"
  ],
  "View previous applications": "viewPreviousApplications",
  "Create Case Link": "createBailCaseLink",
  "Confirm detention location": "confirmDetentionLocation",
  "Update Interpreter Booking Status": "updateInterpreterBookingStatus",
  "Case listing": "caseListing",
  "Force case to the hearing state": "forceCaseToHearing",
  "Change Tribunal Centre": "changeTribunalCentre",
  "Upload a recording file for the hearing": "uploadHearingRecording",
};
